### ISSUE TITLE
BL Touch

### ISSUE THREAD

**Issue by danielbors72** [makerbase-mks/MKS-RUMBA32#1]
how do i connect bltouch?

**Comment by makerbase-mks** [comment]
1. You can connect BLTOUCH to P15, but you may need to adjust the BLTOUCH line order to ensure normal use.
![image](https://user-images.githubusercontent.com/12979070/76608248-42c1af00-6550-11ea-8855-3643e6b40022.png)
2. Add servo_pin define in pins_MKS_RUMBA32.h
![image](https://user-images.githubusercontent.com/12979070/76608292-579e4280-6550-11ea-91c5-7e4d55a3f205.png)
3. You need enable BLTOUCH(configuration.h)
![image](https://user-images.githubusercontent.com/12979070/76608410-84eaf080-6550-11ea-83d1-55e3b5fa0628.png)

**Comment by danielbors72** [comment]
if you use TMC2209 UART mode, and BLTOUCH with PD15 pin, mainboard will not work!
Why?

**Comment by makerbase-mks** [comment]
This may conflict with the UART pin, so SERVO_PIN need to redefine it, such as using PB8 or PB9 pin
![image](https://user-images.githubusercontent.com/12979070/78623390-1cc2cc80-78ba-11ea-8f3c-ed5b77f27b10.png)

**Comment by makerbase-mks** [comment]
@danielbors72 Sorry, I did n’t notice the problem of pin conflict at the beginning

**Comment by phongshader** [comment]
> This may conflict with the UART pin, so SERVO_PIN need to redefine it, such as using PB8 or PB9 pin 
>
redefine the **E1 TX pin** or the **SERVO_PIN**?

**Comment by edriyin1** [comment]
Hello, I tried attaching new arrived 3D Touch sensor. I defined Servo Pin PB8 and gave 5V. But It didin't work. Can you help me?

**Comment by alex18881** [comment]
Hello. I see this issue is closed, but I'm experiensing an issue with wiring my 3Dtouch. On my previous Rumba it works great but when I connect it to my new mks rumba32 it refuses to trigger x min endstop. All commands staw, deploy and self test work ok and when it starts bed leveling the bed just smashes into the nozzle.

**Comment by jwdriessen** [comment]
Dear Makerbase-mks,
I have a Rumba32 V1.0 board (BigTreeTech) with 4 TMC 2209 stepper drivers in UART mode.
The documentation of BTT is very crappy.
I would like to use a BL touch and we should use the PB8 or PB9 pin (part of the encoder) according to your comments.
But is is totally unclear to me **which pin** of the encoder belongs to PB8. 
Would you be so kind to point out where the BL touch sensor wire should be connected? (for mechanical people)
And maybe some hints how to get this thing working?
Marlin 1.19 was a LOT easier but after 2 weeks searching the internet I am on the point of throwing the board out of the window.
