### ISSUE TITLE
12v pwr select

### ISSUE THREAD

**Issue by phongshader** [makerbase-mks/MKS-RUMBA32#10]
I don't see any documentation on how to set the jumpers for 12v pwr select.
<img width="30" alt="Screen Shot 2020-06-06 at 9 12 58 AM" src="https://user-images.githubusercontent.com/38082624/83949096-c77e3b00-a7d6-11ea-9162-db54583945b9.png">
Jump pin1 to pin2 or pin2 to pin3 for 12v power?

This all should be in a manual for basic settings!

**Comment by makerbase-mks** [comment]
Hi! 
Select 2-3 pin, you will get 12V power
Select 1-2 pin, you will get input power as your FAN power
