### ISSUE TITLE
FAN0 not turning on

### ISSUE THREAD

**Issue by phongshader** [makerbase-mks/MKS-RUMBA32#11]
If I run a m106 command FAN0 does not turn on however FAN0 led does light up. The voltage at the fan terminal after a m106 s255 is 1.39 and s128 is .93, s0 is .10. I have a 12v power supply and the power select is jumped to vin-vout. I tried vout-12v with the same result.

**Comment by makerbase-mks** [comment]
Hi! You need set your marlin firmware in configuration.h, you can refer to MKS RUMBA32 wiki about FAN output voltage 
link: https://github.com/makerbase-mks/MKS-RUMBA32/wiki/About-FAN-output-voltage-2.3V
