### ISSUE TITLE
TMC5160, SPI connection error

### ISSUE THREAD

**Issue by ogsv** [makerbase-mks/MKS-RUMBA32#2]
I am having difficulties using my TMC5160 v.1.2 drivers from bigtreetech with a v.1.0 RUMBA32 from Makerbase. I've tested many different builds of Marlin, and also the MK4duo firmware - all with the same result; "Testing X connection... Error: All LOW"

Then I came across this issue posted by @repetier on the @Aus3D github page: https://github.com/Aus3D/RUMBA32/issues/17

So I guess my board also might have this issue? Any suggestions on how to fix it, would be more than welcome!

Update: I guess I confirmed the pinout error: Pin 5 is connected to !RST, when it should be MISO.
![image](https://user-images.githubusercontent.com/48555165/76698856-b9bd8b80-66a7-11ea-88c2-42c2588eb8f4.png)
![image](https://user-images.githubusercontent.com/48555165/76698874-d6f25a00-66a7-11ea-847e-868ec607caa7.png)

**Comment by repetier** [comment]
See https://github.com/Aus3D/RUMBA32/issues/12 there chrissbar tells how to fix it with a simple bridge which is also what I did and afterwards it worked. So if MKS made a 1:1 copy they probably also copied the wrong pin positions making the jumper not work as expected.

**Comment by ogsv** [comment]
Thanks a lot @repetier , problem solved! 😃 I'll leave the issue open, in case MKS should want to revise their board layout.
O/T: Did you get your firmware to work reliably on this board? I'd love to test it!
![image](https://user-images.githubusercontent.com/48555165/76700714-96e8a280-66ba-11ea-9632-ac240b701585.png)

**Comment by makerbase-mks** [comment]
Hi! Thank you for your feedback. I will add instructions for connecting to the TMC2130 or TMC5160 FAQ on the MKS RUMBA32 wiki page. Thanks again, we will improve this issue in the new version 1.1 and add BLTOUCH interface and so on

**Comment by makerbase-mks** [comment]
Hi! I have created a FAQ to help users solve "TMC CONNECTION ERROR". Link: https://github.com/makerbase-mks/MKS-RUMBA32/wiki/About-RUMBA32-TMC-SPI-"CONNECTION-ERROR"-FAQ

**Comment by phongshader** [comment]
Looks like there are 2 different solutions to this issue, jumping  X-RST >  SPI1  or jumping pin5 X-RST > pin6, sleep on the driver shown here https://github.com/makerbase-mks/MKS-RUMBA32/wiki/About-RUMBA32-TMC-SPI-"CONNECTION-ERROR"-FAQ. Which is correct or will both solutions accomplish the same thing? If going with the makerbase solution does that preclude using non spi drivers  like this solution does?

**Comment by makerbase-mks** [comment]
Hi! @phongshader 
Their effect is the same.

**Comment by phongshader** [comment]
Would this work as a solution, instead of soldering the board?
![open](https://user-images.githubusercontent.com/38082624/81218370-f3698f00-8f92-11ea-8a46-d911e3440f17.jpg)
![jumpered](https://user-images.githubusercontent.com/38082624/81218382-f82e4300-8f92-11ea-9e40-ce97a2a4cfad.jpg)

**Comment by ogsv** [comment]
@phongshader , theoretically, that should also work. Now that you've done it already, why don't you tell us? :)

**Comment by phongshader** [comment]
I would but I don't have the board yet.

**Comment by labotecno** [comment]
> 
> 
> @phongshader , theoretically, that should also work. Now that you've done it already, why don't you tell us? :)



> 
> 
> I would but I don't have the board yet.

hello it is working like this way ?

**Comment by phongshader** [comment]
it did not work but I did get a work around that did not require any soldering. all the steps are here https://old.cultivate3d.com/forums/viewtopic.php?f=6&t=299&sid=ce972bfdc1f26035f8679d28e6a662c2

**Comment by studiodyne** [comment]
Or , you can also , use a thin wire , place it inside the 2 dupont connectors holes , and plug the drivers
10 sec , no tools , no heat , no electrostatic fatality
No warranty break

😄
