### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by RepRapThailand** [makerbase-mks/MKS-RUMBA32#28]
Hi.

Atom 1.52.0 PlatformIO 5.0.3

Compiling .pio\build\mks_rumba32\FrameworkArduino\stm32\usb\usbd_desc.c.o
C:\Users\krp\.platformio\packages\framework-arduinoststm32\cores\arduino\stm32\usb\usbd_desc.c:46:4: error: #error "USB VID or PID not specified"
   46 |   #error "USB VID or PID not specified"
      |    ^~~~~
In file included from C:\Users\krp\.platformio\packages\framework-arduinoststm32\system\Middlewares\ST\STM32_USB_Device_Library\Core\Inc/usbd_core.h:30,
                 from C:\Users\krp\.platformio\packages\framework-arduinoststm32\cores\arduino\stm32\usb\usbd_desc.c:21:
C:\Users\krp\.platformio\packages\framework-arduinoststm32\cores\arduino\stm32\usb\usbd_desc.c:160:10: error: 'USBD_PID' undeclared here (not in a function); did you mean 'USBD_VID'?

**Comment by mks-viva** [comment]
Hi! I think this is caused by some libraries on the compilation platform. At this stage, people are more willing to use Vscode to compile firmware.

**Comment by RepRapThailand** [comment]
Which version should I install, both VSC and PIO?

**Comment by mks-viva** [comment]
Like this: https://github.com/makerbase-mks/MKS-Robin-Nano-V2.X/wiki/Marlin_firmware

**Comment by RepRapThailand** [comment]
I try VScode 1.51.1 and PIO 2.2.1 and same error.

**Comment by RepRapThailand** [comment]
Building in release mode
Compiling .pio\build\mks_rumba32\FrameworkArduino\stm32\usb\usbd_desc.c.o
Compiling .pio\build\mks_rumba32\FrameworkArduino\stm32\usb\usbd_ep_conf.c.o
C:\Users\krp\.platformio\packages\framework-arduinoststm32\cores\arduino\stm32\usb\usbd_desc.c:46:4: error: #error "USB VID or PID not specified"
   46 |   #error "USB VID or PID not specified"
      |    ^~~~~
In file included from C:\Users\krp\.platformio\packages\framework-arduinoststm32\system\Middlewares\ST\STM32_USB_Device_Library\Core\Inc/usbd_core.h:30,
                 from C:\Users\krp\.platformio\packages\framework-arduinoststm32\cores\arduino\stm32\usb\usbd_desc.c:21:
C:\Users\krp\.platformio\packages\framework-arduinoststm32\cores\arduino\stm32\usb\usbd_desc.c:160:10: error: 'USBD_PID' undeclared here (not in a function); did you mean 'USBD_VID'?
  160 |   LOBYTE(USBD_PID),           /* idProduct */
      |          ^~~~~~~~
C:\Users\krp\.platformio\packages\framework-arduinoststm32\system\Middlewares\ST\STM32_USB_Device_Library\Core\Inc/usbd_def.h:275:32: note: in definition of macro 'LOBYTE'
  275 | #define LOBYTE(x)  ((uint8_t)((x) & 0x00FFU))
      |                                ^
*** [.pio\build\mks_rumba32\FrameworkArduino\stm32\usb\usbd_desc.c.o] Error 1
================================================================================================== [FAILED] Took 5.53 seconds ==================================================================================================

Environment    Status    Duration
-------------  --------  ------------
mks_rumba32    FAILED    00:00:05.533
============================================================================================= 1 failed, 0 succeeded in 00:00:05.533 =============================================================================================
The terminal process "C:\Users\krp\.platformio\penv\Scripts\pio.exe 'run', '--environment', 'mks_rumba32'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by mks-viva** [comment]
Did you modify the firmware? Can you provide your firmware to me?

**Comment by RepRapThailand** [comment]
I have not modified. Link  https://github.com/makerbase-mks/MKS-RUMBA32/tree/master/Firmware/Marlin-bugfix-2.0.x

**Comment by RepRapThailand** [comment]
I try  compile on another computer and same error.

**Comment by RepRapThailand** [comment]
Do I have to connect the board while build?

**Comment by mks-viva** [comment]
Haha! You can download offical marlin and change it, MKS RUMBA32 path marlin firmware have not update to the latest version marlin firmware.

**Comment by RepRapThailand** [comment]
Verbose mode can be enabled via `-v, --verbose` option
In file included from buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/MarlinConfig.h:34,
                 from buildroot/share/PlatformIO/scripts/common-dependencies.h:31:
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../pins/pins.h:776:6: error: #error "Unknown MOTHERBOARD value set in Configuration.h"
  776 |     #error "Unknown MOTHERBOARD value set in Configuration.h"
      |      ^~~~~
CalledProcessError: Command '"C:\Users\krp\.platformio\packages\toolchain-gccarmnoneeabi\bin\arm-none-eabi-g++.exe" -D__MARLIN_FIRMWARE__ -DSTM32F4xx -DARDUINO_RUMBA32_F446VE -DARDUINO_ARCH_STM32 -DBOARD_NAME=\"RUMBA32_F446VE\" -DSTM32F446xx -DUSBCON -DUSBD_VID=0x8000 -DUSB_MANUFACTURER=\"Unknown\" -DUSB_PRODUCT=\"RUMBA32_F446VE\" -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_CDC -DDISABLE_GENERIC_SERIALUSB -DHAL_UART_MODULE_ENABLED -D__MARLIN_DEPS__ -w -dM -E -x c++ buildroot/share/PlatformIO/scripts/common-dependencies.h' returned non-zero exit status 1.:
  File "C:\Users\krp\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 168:
    env.SConscript(item, exports="env")
  File "C:\Users\krp\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\krp\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\krp\Documents\PlatformIO\Projects\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 287:
    apply_features_config()
  File "C:\Users\krp\Documents\PlatformIO\Projects\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 118:
    if not env.MarlinFeatureIsEnabled(feature):
  File "C:\Users\krp\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\Users\krp\Documents\PlatformIO\Projects\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 263:
    load_marlin_features()
  File "C:\Users\krp\Documents\PlatformIO\Projects\Marlin-bugfix-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 251:
    define_list = subprocess.check_output(cmd, shell=True).splitlines()
  File "C:\Users\krp\.platformio\python3\lib\subprocess.py", line 411:
    **kwargs).stdout
  File "C:\Users\krp\.platformio\python3\lib\subprocess.py", line 512:
    output=stdout, stderr=stderr)

**Comment by RepRapThailand** [comment]
![1606474391023](https://user-images.githubusercontent.com/15525407/100441955-da186380-30d9-11eb-9898-05351df0b5f7.jpg)

**Comment by mks-viva** [comment]
You need define BOARD_RUMBA32_MKS
![image](https://user-images.githubusercontent.com/16629551/100442471-0d132500-30e3-11eb-8da9-7635543fb894.png)

**Comment by RepRapThailand** [comment]
![1606474759301](https://user-images.githubusercontent.com/15525407/100442475-ac7fea00-30da-11eb-9f6b-3ad2726ce6a4.jpg)

**Comment by RepRapThailand** [comment]
![1606474939634](https://user-images.githubusercontent.com/15525407/100442734-17c9bc00-30db-11eb-9773-d01a072f59a1.jpg)

**Comment by RepRapThailand** [comment]
Back to the same failure.

**Comment by mks-viva** [comment]
What screen are you using? I test a firmware and provide it to you

**Comment by RepRapThailand** [comment]
MKS TFT35 V1.0 and RepRapDiscount Full Graphic Smart Controller.

**Comment by RepRapThailand** [comment]
Which version do you use for VScode and Platformio?

**Comment by mks-viva** [comment]
[update firmware bin file.zip](https://github.com/makerbase-mks/MKS-RUMBA32/files/5607622/update.firmware.bin.file.zip)
1. Download it
2. MKS RUMBA32 enter DFU mode(Press down BOOT ， connect to PC by USB)
![image](https://user-images.githubusercontent.com/16629551/100445405-03d88700-30e8-11eb-9b57-f0e30f8683d7.png)
3. Run Upload.bat
![image](https://user-images.githubusercontent.com/16629551/100445464-1783ed80-30e8-11eb-8fba-77440084a040.png)
![image](https://user-images.githubusercontent.com/16629551/100445500-2e2a4480-30e8-11eb-9499-75182736384d.png)
4. Test is ok
[RUMBA32+TFT35+LCD12864 TEST.zip](https://github.com/makerbase-mks/MKS-RUMBA32/files/5607650/RUMBA32%2BTFT35%2BLCD12864.TEST.zip)
![image](https://user-images.githubusercontent.com/16629551/100446181-4fd7fb80-30e9-11eb-9832-49e9976ee92b.png)

**Comment by mks-viva** [comment]
The firmware link is: https://github.com/makerbase-mks/MKS-RUMBA32/blob/master/Firmware/Marlin-2.0.7.2.zip

**Comment by RepRapThailand** [comment]
Successful with your upload.bat but TFT35 not responding,  full graphic smart controller working.

**Comment by RepRapThailand** [comment]
![1606489134989](https://user-images.githubusercontent.com/15525407/100461980-22487d80-30fc-11eb-8e0b-36b3cf01f413.jpg)

**Comment by RepRapThailand** [comment]
[VID_20201127_215531.zip](https://github.com/makerbase-mks/MKS-RUMBA32/files/5608422/VID_20201127_215531.zip)

**Comment by RepRapThailand** [comment]
> The firmware link is: https://github.com/makerbase-mks/MKS-RUMBA32/blob/master/Firmware/Marlin-2.0.7.2.zip

What version of VScode and Platformio are you using?

I use 1.51.1 and 2.2.1 and st stm32 9.0.

**Comment by mks-viva** [comment]
> > The firmware link is: https://github.com/makerbase-mks/MKS-RUMBA32/blob/master/Firmware/Marlin-2.0.7.2.zip
> 
> What version of VScode and Platformio are you using?
> 
> I use 1.51.1 and 2.2.1 and st stm32 9.0.

Haha! I use MKS-Marlin2.0-Compile.exe : https://github.com/makerbase-mks/MKS-Marlin2.0-Compile-Tool

**Comment by mks-viva** [comment]
> Successful with your upload.bat but TFT35 not responding, full graphic smart controller working.

You need set MKS TFT35 baudrate to 250000 by config file

**Comment by RepRapThailand** [comment]
> > Successful with your upload.bat but TFT35 not responding, full graphic smart controller working.
> 
> You need set MKS TFT35 baudrate to 250000 by config file

yes, baudrate 250000

![1606567364391](https://user-images.githubusercontent.com/15525407/100515906-4e263a80-31b2-11eb-8e9e-e3eb39138a1f.jpg)

**Comment by RepRapThailand** [comment]
ok, success!
ขอบคุณมาก
