### ISSUE TITLE
All Endstops not working

### ISSUE THREAD

**Issue by gsart84** [makerbase-mks/MKS-RUMBA32#29]
Hello

sorry for my bad english

i have a MKS Rumba32 V1.0 Board and i loadet Marlin from MKS github.
All Endstop does not work.

Previously there was a old Rumba Board in my Printer ans all endstops working fine.

can anyone help? 

i attached the files

[Marlin.zip](https://github.com/makerbase-mks/MKS-RUMBA32/files/5633904/Marlin.zip)

**Comment by mks-viva** [comment]
Hi! Ok i will check it tomorrow.

**Comment by gsart84** [comment]
Hello

got it.

Bending the diag pin on stepper driver solve the problem!

**Comment by mks-viva** [comment]
Yes, TMC2209 will output a singal by diag pin, MKS RUMBA32 connected it to endstop signal pin by 0603-0Ω
![image](https://user-images.githubusercontent.com/16629551/101231008-98904580-36e3-11eb-81d5-1d4764059310.png)
![image](https://user-images.githubusercontent.com/16629551/101231026-ad6cd900-36e3-11eb-856c-0a05911d1de5.png)

**Comment by mks-viva** [comment]
I will close this issues temporarily
