### ISSUE TITLE
Rumba32 TMC2209

### ISSUE THREAD

**Issue by ghost** [makerbase-mks/MKS-RUMBA32#3]
Hello, when i select TMC2209 then compile error in Arduino!

SanityCheck.h:2071:4: error: #error "TMC2208 Software Serial is supported only on AVR, LPC1768, STM32F1 and STM32F4 platforms."

I have TMC2209!!!!!

**Comment by ghost** [comment]
Hello, why config and jumpering for UART on RUMBA32_MKS???  Thanks

**Comment by makerbase-mks** [comment]
Hi! At present, RUMBA32 does not support TMC2209 UART mode function, which is mainly Marlin firmware. But the UART mode is set as follows:
![image](https://user-images.githubusercontent.com/12979070/77976700-4155fc00-7330-11ea-800c-d3f6bf860464.png)

**Comment by ghost** [comment]
Hello, I got the TMC2209 with Rumba32 running today with the dev version 2.1.0 of Marlin and the drivers are recognized by M122 and displayed as a test ok! 
It is important to have 12V on the board, only USB outputs TMC errors
22:12:22.118 : Testing X connection... OK
22:12:22.122 : Testing Y connection... OK
22:12:22.126 : Testing Z connection... OK
22:12:22.130 : Testing E connection... OK
22:12:22.134 : Testing E1 connection... OK


Hallo, habe heute mit der dev Version 2.1.0 von Marlin die TMC2209 mit Rumba32 zum laufen bekommen und die Treiber werden bei M122 erkannt und als Test ok angezeigt! 
Wichtig ist 12V müssen am Board anliegen nur USB gibt TMC fehler aus

22:12:22.118 : Testing X connection... OK
22:12:22.122 : Testing Y connection... OK
22:12:22.126 : Testing Z connection... OK
22:12:22.130 : Testing E connection... OK
22:12:22.134 : Testing E1 connection... OK

![20200331_221304](https://user-images.githubusercontent.com/15977233/78070974-f3c3a880-739c-11ea-8dda-a590f7d35732.jpg)

**Comment by makerbase-mks** [comment]
Can the motor run normally? Is everything normal?

**Comment by ghost** [comment]
Yes Motor run

**Comment by ghost** [comment]
Compile with Visual Studio Code

**Comment by ghost** [comment]
One Problem found. When i set eeprom on this no function no eeprom fround on display.

Can help me?

**Comment by makerbase-mks** [comment]
Hi! @dennis0212  STM32 series MCUs do not have EEPROM, but when the Marlin program handles this part of the function, it should be written to the flash memory using analog mode. You can see this part of the function

**Comment by ghost** [comment]
On Version 2.0.5.3 function eprom on 2.1 no eprom. Can you this fixed ?

**Comment by fjriosp** [comment]
I'm unable to get it working.

If I set any Stepper to TMC2209 (UART mode) on Marlin it stucks on boot Marlin logo.

Any help?

**Comment by ghost** [comment]
Hello, Marlin 1.2-dev compile with Visual Studio Code with full graphik display is working on rumba32 with uart.

**Comment by ghost** [comment]
[Marlin-dev-2.1.x.zip](https://github.com/makerbase-mks/MKS-RUMBA32/files/4489360/Marlin-dev-2.1.x.zip)

**Comment by fjriosp** [comment]
I can't get it working.

Could you send me your sources?

**Comment by fjriosp** [comment]
I got the full graphics working, but the steppers don't work.

Without uart the don't step. The step pin is always low.

With uart hangs on marlin logo.

**Comment by ghost** [comment]
[Configuration.txt](https://github.com/makerbase-mks/MKS-RUMBA32/files/4490992/Configuration.txt)
[Configuration_adv.txt](https://github.com/makerbase-mks/MKS-RUMBA32/files/4490993/Configuration_adv.txt)


Here my config this is for RUMBA_MKS32

**Comment by fjriosp** [comment]
Ok, now it works.

There is a problem in the STM32 arduino core 1.8.0 and breaks the STM32 timers so the watchdog kills the mcu in a boot loop.

Now I'm using a previous version of STM32 platform on platformio and works with serial.

Thanks!

**Comment by ghost** [comment]
yes, you must compile with visual code on this is no problem with stm32cores
