### ISSUE TITLE
[Q] pinout and button ?

### ISSUE THREAD

**Issue by DrumClock** [makerbase-mks/MKS-RUMBA32#31]
Hi, I have a few questions:

1) What is the "USER" button for?
2) can the points on the PCB marked TP3, TP4, and TP5 be used as additional I / O pins?

Thank you.

**Comment by mks-viva** [comment]
Hi!
1. User button you can define it as kill_pin
2. TP3: PB10，TP4: PA15，TP5: PD11，you can define it to other function

**Comment by DrumClock** [comment]
HI, thank you very much.
Is it possible to define TP3-TP5 pins as PWM for servo control use?

**Comment by mks-viva** [comment]
Hi! PB10/PA15 is PWM pin
![image](https://user-images.githubusercontent.com/16629551/104982677-22069780-5a46-11eb-9860-0cd9263fad2e.png)
![image](https://user-images.githubusercontent.com/16629551/104982698-2af76900-5a46-11eb-9348-f24c9057839c.png)

**Comment by DrumClock** [comment]
Thanks @mks-viva , I have one more question.

If I use the TMC 2209 UART-Mode driver, will I be able to use the I / O pins on the EXP 3 connector
 for other functions (eg 2x servo, Neopixel LED, etc.)?

**Comment by mks-viva** [comment]
No, because it has been used in TMC2209 uart

**Comment by DrumClock** [comment]
Hi, I also noticed it while studying the schematic.

If I compare it, for example, with the board ROBIN_PRO
 which uses` SERIAL_TX_PIN = SERIAL_RX_PIN .... PD5`

Query:

What if I remove resistors R90 to R95 and define them
same `SERIAL_RX_PIN = SERIAL_TX_PIN .... PC14`

Then I could use EXP3 without limiting the UART mode.

Thank you

**Comment by mks-viva** [comment]
Yes, it can be done. Currently STM32 supports 1 IO for UART mode setting

**Comment by DrumClock** [comment]
Hi @mks-viva 
OK, I'm waiting for the delivery of the MKS Rumba32 board. 
I'll run a test and give info on how it works.

Edit the pins_RUMBA32_MKS file. 

```
//
  // Software serial
  //
  #define X_SERIAL_TX_PIN                   PC14   		// desoldering resistor R90 on board
  #define X_SERIAL_RX_PIN                   PC14

  #define Y_SERIAL_TX_PIN                   PE4   		// desoldering resistor R91 on board
  #define Y_SERIAL_RX_PIN                   PE4

  #define Z_SERIAL_TX_PIN                   PE0  		// desoldering resistor R92 on board
  #define Z_SERIAL_RX_PIN                   PE0

  #define E0_SERIAL_TX_PIN                  PC13   		// desoldering resistor R93 on board
  #define E0_SERIAL_RX_PIN                  PC13

  #define E1_SERIAL_TX_PIN                  PD5   		// desoldering resistor R94 on board
  #define E1_SERIAL_RX_PIN                  PD5
 
  #define E2_SERIAL_TX_PIN                  PD1   		// desoldering resistor R95 on board
  #define E2_SERIAL_RX_PIN                  PD1
  
  // Reduce baud rate to improve software serial reliability
  #define TMC_BAUD_RATE                    19200
  
#endif

//
// define pin EXP3
//

#define SERVO0_PIN                          PD15        // SWITCHING EXTRUDER E0,E1
#define SERVO1_PIN                          PD14        // PWM 1
#define POWER_LOSS_PIN 						PA3		    // Pin to detect power loss
#define NEOPIXEL_PIN     					PA4         // LED driving pin	
#define E0_AUTO_FAN_PIN 					PD13		// FAN HOTEND 0 - external MOSFET chanel
#define E1_AUTO_FAN_PIN 					PD12		// FAN HOTEND 1 - external MOSFET chanel

/**   
* Reserved for I2C and UART	1
*
*  ENC_1 to 4								PB8			// I2C - SCL 
*  ENC_1 to 4	 							PB9			// IC2 - SDA 
*  AUX-1 Use UART 1 - TX					PA9         // #define SERIAL_PORT_2 1
*  AUX-1 Use UART 1 - RX					PA10        // #define SERIAL_PORT_2 1  
*
*/

//
// Z Probe (when not Z_MIN_PIN)
//
#ifndef Z_MIN_PROBE_PIN
  #define Z_MIN_PROBE_PIN                   PD9
#endif

//
// Runout Probe (when not Y_MAX_PIN)
//
#ifndef Y_MAX_PIN
  #define FIL_RUNOUT1_PIN			        PD8
#endif
```

**Comment by mks-viva** [comment]
But you need test it. So, i will close this issues temporarily.

**Comment by DrumClock** [comment]
@mks-viva 
Please help,
I can't access the record to FW Marlin.
The device is installed in the manager, but when I connect the board,
Win10 does not load the STM32 BOOTLOADER driver. 

![bootloader](https://user-images.githubusercontent.com/64655979/107813460-baa3e500-6d70-11eb-807f-bdde7210ab52.PNG)

method:
1. connect the Rumba board via USB to the computer
2. press the RESET button together with BOOT

**Comment by DrumClock** [comment]
so the STM32 BOOTLOADER no longer appears at all in the device manager ....
