### ISSUE TITLE
BUG - MKS Rumba32 and Bigtreetech TFT 35 E3 V1.0

### ISSUE THREAD

**Issue by DrumClock** [makerbase-mks/MKS-RUMBA32#33]
info: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1624

**Comment by DrumClock** [comment]
It is said that this is not a problem of Bigtreetech TFT panel but incompatibility of MKS Rumba32
 .... see communication on the link above ...

**Comment by mks-viva** [comment]
Hi, you connect it by Aux-1 interface

**Comment by DrumClock** [comment]
The AUX-1 interface only works from TFT mode and some functions are inaccessible (eg IDEX mode).
Therefore I also have connected EXP1 and EXP2 interfaces for Mod LCD 12864.

There is a problem that the MKS uses pin PB2 (BOOT1) as pin BTN and it is a problem to switch the board to DFU mode because this pin is permanently in H (3.3V) from the TFT panel.

The solution is to remap both HW and SW pin BTN to another.
