### ISSUE TITLE
(Q) - change pin function

### ISSUE THREAD

**Issue by DrumClock** [makerbase-mks/MKS-RUMBA32#35]
Hi, @mks-viva 

It is possible to define pins:

PB8 -  (SCL)
PB9 - (SDA)
PA4  - (A9)
PA3  - (A10)

As I/O digital pins for switching transistors or endstop sensors?

**Comment by mks-viva** [comment]
Yes, you can

**Comment by DrumClock** [comment]
I wanted to define pin PB4 (A9) instead of PB2 for BTN ...... but it didn't work.
Here are the reasons why: # 33 (comment)
