### ISSUE TITLE
BLTouch+TMC2209 UART mode

### ISSUE THREAD

**Issue by danielbors72** [makerbase-mks/MKS-RUMBA32#5]
If you use TMC2209 UART mode, and BLTOUCH with PD15 pin, MKS_RUMBA32 mainboard will not work, it blocks right after the logo Marlin appears!
For tmc2209_standalone and BLTouch work or tmc2209 UART mode whitout BLTouch define, work also!
Please, help me!

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-RUMBA32/issues/1
