### ISSUE TITLE
Rumba32+Marlin2

### ISSUE THREAD

**Issue by dupaser** [makerbase-mks/MKS-RUMBA32#6]
Good afternoon, I have a problem with marlin2 and rumba32 mks. I can't make it work for the second day. I tried all the firmware Marlin of the second version. The problem is that the Board restarts for no reason. I tried booting a simple program to check the connection and it works.
![VXku7mmsCFQ](https://user-images.githubusercontent.com/63799469/79469832-59549d80-8009-11ea-8982-a853d072d330.jpg)

[video-1587046434.zip](https://github.com/makerbase-mks/MKS-RUMBA32/files/4487808/video-1587046434.zip)

**Comment by Bolino08f** [comment]
Hello, in configuration.h :
#define SERIAL_PORT -1
#define SERIAL_PORT_2 1.

**Comment by dupaser** [comment]
Yes, it was true
![Снимок экрана (12)](https://user-images.githubusercontent.com/63799469/79632592-02fe7080-8169-11ea-964a-f93b3d94f09d.png)

**Comment by Bolino08f** [comment]
You have tmc2208/2209 ? In soft uart ?

**Comment by dupaser** [comment]
I plan to put 2209 but when loading the Board is empty

**Comment by Bolino08f** [comment]
Yes but in configuration.h is declared ?

**Comment by dupaser** [comment]
I tried it in two ways yes/no

**Comment by Bolino08f** [comment]
Your library of STM32 are 6.1.0 ? If yes, use ver 6.0.0

**Comment by dupaser** [comment]
This is a good option. How can I view this in VS code?

**Comment by dupaser** [comment]
![Снимок экрана (14)](https://user-images.githubusercontent.com/63799469/79789401-c8f0c280-8352-11ea-8d64-54b82e780a33.png)

**Comment by dupaser** [comment]
I have 6.1.0, install 6.0.0

**Comment by Bolino08f** [comment]
In platforms

**Comment by dupaser** [comment]
Yes! Yes! This is great! Thank you very much! Works, does not restart.
