### ISSUE TITLE
Flash without button press

### ISSUE THREAD

**Issue by lorenzing** [makerbase-mks/MKS-RUMBA32#7]
Hi,
I ask you if I can flash the board without pressing the boot and reset keys, since the card is in an awkward position in the printer. Thank you very much for helping.

Lorenzo

**Comment by makerbase-mks** [comment]
Hi! @lorenzing 
This motherboard is a continuation of the original version of the function, currently only this way, we are sorry for this!

**Comment by leseaw** [comment]
if you use Marlin-Kimbra, you don't need it anymore.
There's an extra command for boot mode.

**Comment by makerbase-mks** [comment]
Yes, unless there is a bootloader
