### ISSUE TITLE
Mks pwc conection

### ISSUE THREAD

**Issue by calabia2000** [makerbase-mks/MKS-RUMBA32#8]
Good, I would like to know how I can connect the mks pwc on this board, I also have the mks pad7 screen

**Comment by makerbase-mks** [comment]
Hi! At present, the MKS PAD function is not yet perfect, it will be better to use PWC with MKS TFT.

**Comment by makerbase-mks** [comment]
Hi! You can refer to https://github.com/makerbase-mks/MKS-Robin-E3-E3D/wiki/Upgrade-with-MKS-PWC
