### ISSUE TITLE
jumpers to set for DRV8825 drivers

### ISSUE THREAD

**Issue by phongshader** [makerbase-mks/MKS-RUMBA32#9]
I don't see any documentation on how to set the jumpers for the drivers. If I want to set up x and y drivers to 16 micro steps and z to 32 micro steps. SLP MS3 MS2 MS1 or maybe I don't understand how this works. Documentation?

**Comment by makerbase-mks** [comment]
Jumpers set like this:
![image](https://user-images.githubusercontent.com/12979070/83934117-de298f80-a7e0-11ea-87cc-987cac3a027d.png)

**Comment by phongshader** [comment]
[image: Screen Shot 2020-06-05 at 7.35.46 PM.png]

[image: Screen Shot 2020-06-05 at 7.35.37 PM.png]
If I wanted to set micro stepping 16 what jumpers would I connect? MS1=16,
MS2=32, MS3=64?

**Comment by makerbase-mks** [comment]
You need acord to DRV8825 micro step set M1,M2,M3
![image](https://user-images.githubusercontent.com/12979070/83936157-408b8b80-a7f3-11ea-8613-925b93baed4f.png)

**Comment by phongshader** [comment]
The pin numbers you referenced were from AUS3D board not the MKS board. the MKS pins are SLP, M2, M1, M0. 
1/16
<img width="174" alt="x16" src="https://user-images.githubusercontent.com/38082624/83948698-bd0e7200-a7d3-11ea-9cec-4e8ba6970e48.png">
1/32
<img width="174" alt="x32" src="https://user-images.githubusercontent.com/38082624/83948647-6739ca00-a7d3-11ea-813f-0605571343e5.png">
Is this correct?

**Comment by makerbase-mks** [comment]
Yes, set as your picture
